### ISSUE TITLE
Forge complains about tcpdump missing , even though TCPDUMP=False

### ISSUE THREAD

**Issue by tomaszmrugalski** [isc-projects/forge#22]
This is just a minor issue as the warning doesn't seem to affect anything.

my init_all.py has TCPDUMP=False (which is the default). When I run a test, I see this:

``` bash
$ ./run_test.py -6 -n v6.client.classification.onesubnet.docsis3.advertise.success
WARNING: Failed to execute tcpdump. Check it is installed and in the PATH
...
```

This warning is produced only when I run the code as regular user, it does not appear when run as root. I do have tcpdump installed in /usr/sbin/, so the regular user can't find it. That does explain why the warning is produced for regular user. However, the issue here is that Forge should not even try to find it, because TCPDUMP is set to False. At least that's my understanding of the TCPDUMP variable. If tcpdump is used everytime and that variable only governs whether the capture is saved after the test, please update its description.

**Comment by wwencel** [comment]
migrated to gitlab https://gitlab.isc.org/isc-private/qa-dhcp/issues/117
